#ifndef TILETYPE_H
#define TILETYPE_H

enum TileType // m8
{
    EMPTY_TILE,
    GRASS_MIDDLE,
    GRASS_RIGHT,
    GRASS_LEFT,
    DIRT_LEFT,
    DIRT_MIDDLE,
    DIRT_RIGHT,
    WOODEN_BOX,
    DIRT_LEFT_GRASS_RIGHT,
    ROUND_DIRT_UPPER_LEFT,
    DIRT_BOTTOM,
    DIRT_MIDDLE_LEFT,
    DIRT_BACKGROUND,
    ROUND_DIRT_UPPER_RIGHT,
    DIRT_BACKGROUND_TOP,
    DIRT_TOP,
    DIRT_TOP_LEFT,
    DIRT_TOP_PILLAR,
    DIRT_MIDDLE_PILLAR,
    DIRT_BOTTOM_PILLAR,
    DIRT_TOP_LEFT_GRASS_RIGHT,
    GRASS_SLOPE_UP_LEFT,
    GRASS_TOP_LEFT,
    GRASS_TOP,
    ROOTS_BOTTOM,
    SLOPE_TOP,
    SLOPE_MIDDLE,
    MAX_TILES
};

#endif // !TILETYPE_H
